title: My Blog
author: Shafaq Ul Bahar
email: shafaqulbahar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello World!
  I am a 16 year old girl from Multan, Pakistan.

# social links
twitter_username: https://twitter.com/shafaq_ul
github_username:  https://github.com/shafaqulbahar

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
